import sharp from 'sharp';
import { writeFileSync } from 'fs';

// タイムカードアイコンのSVG（時計のデザイン）
const createIconSvg = (size) => `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#0d6efd"/>
      <stop offset="100%" style="stop-color:#0056b3"/>
    </linearGradient>
  </defs>
  <!-- 背景（角丸正方形） -->
  <rect x="0" y="0" width="${size}" height="${size}" rx="${size * 0.15}" fill="url(#bg)"/>

  <!-- 時計の外枠 -->
  <circle cx="${size/2}" cy="${size/2}" r="${size * 0.35}" fill="white"/>
  <circle cx="${size/2}" cy="${size/2}" r="${size * 0.30}" fill="#f8f9fa" stroke="#dee2e6" stroke-width="${size * 0.01}"/>

  <!-- 時計の目盛り -->
  ${[0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330].map(angle => {
    const rad = (angle - 90) * Math.PI / 180;
    const inner = size * 0.24;
    const outer = size * 0.28;
    const cx = size / 2;
    const cy = size / 2;
    return `<line x1="${cx + inner * Math.cos(rad)}" y1="${cy + inner * Math.sin(rad)}" x2="${cx + outer * Math.cos(rad)}" y2="${cy + outer * Math.sin(rad)}" stroke="#6c757d" stroke-width="${size * 0.015}" stroke-linecap="round"/>`;
  }).join('\n  ')}

  <!-- 時針（10時10分の位置） -->
  <line x1="${size/2}" y1="${size/2}" x2="${size/2 - size*0.12}" y2="${size/2 - size*0.08}" stroke="#212529" stroke-width="${size * 0.03}" stroke-linecap="round"/>

  <!-- 分針 -->
  <line x1="${size/2}" y1="${size/2}" x2="${size/2 + size*0.08}" y2="${size/2 - size*0.18}" stroke="#212529" stroke-width="${size * 0.02}" stroke-linecap="round"/>

  <!-- 中心点 -->
  <circle cx="${size/2}" cy="${size/2}" r="${size * 0.025}" fill="#0d6efd"/>

  <!-- ICカードマーク（右下） -->
  <rect x="${size * 0.58}" y="${size * 0.65}" width="${size * 0.25}" height="${size * 0.18}" rx="${size * 0.02}" fill="#ffc107" stroke="#e0a800" stroke-width="${size * 0.008}"/>
  <rect x="${size * 0.62}" y="${size * 0.69}" width="${size * 0.08}" height="${size * 0.04}" fill="#fff3cd"/>
</svg>
`;

async function generateIcon(size, filename) {
  const svg = createIconSvg(size);
  const buffer = await sharp(Buffer.from(svg))
    .png()
    .toBuffer();

  const base64 = buffer.toString('base64');
  console.log(`// ${filename} (${size}x${size})`);
  console.log(`const ICON_${size}_BASE64 = '${base64}';`);
  console.log('');

  return base64;
}

async function main() {
  const icon192 = await generateIcon(192, 'icon-192.png');
  const icon512 = await generateIcon(512, 'icon-512.png');

  // Write to a separate file
  const output = `// Auto-generated PWA icons - DO NOT EDIT MANUALLY
// Generated by scripts/generate-icons.mjs

export const ICON_192_BASE64 = '${icon192}';

export const ICON_512_BASE64 = '${icon512}';
`;

  writeFileSync('./src/icons.ts', output);
  console.log('Icons written to src/icons.ts');
}

main().catch(console.error);
